### ISSUE TITLE
Tahoe LTI customizations seem to have no effect on an Tutor installation of Open edX

### ISSUE THREAD

**Issue by RonanFR** [appsembler/tahoe-lti#11] opened 2021-03-18 11:47 UTC
Hi all!
I am encountering some issue while trying to use the Tahoe LTI customizations work wih a Tutor installation of Open edX. Everything seem to work fine on the Tutor side (successful installation of the plugin, apparently correct configuration of XBLOCK_SETTINGS and "Send extra parameters" set to True) but no extra parameter is sent to the LTI Tool (tested with https://lti.tools/saltire/tp). Here is the link to the discussion on Overhang.IO: https://discuss.overhang.io/t/use-appsembler-tahoe-lti-with-tutor/1351
Do you have any idea what may cause the problem?
Thank you very much in advance

**Comment by OmarIthawi** [comment] 2021-05-25 08:56
Thanks @RonanFR. I see that you've found the root cause and it's being addressed by an upstream pull request: https://github.com/edx/xblock-lti-consumer/pull/150

**Closed as completed** 2021-05-25 09:15 UTC
